apiVersion: v1
kind: Secret
metadata:
  name: minecraft-storage-secret
  namespace: minecraft
type: Opaque
data:
  azurestorageaccountname: Base64_REDACTED_VALUE
  azurestorageaccountkey: Base64_REDACTED_VALUE
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: minecraft-bedrock-env
  labels:
    role: service-config
    app: minecraftg
data:
  EULA: "TRUE"
  VERSION: "1.19.40.02"
  GAMEMODE: "survival"
  LEVEL_SEED: "8486214866965744170"
  TICK_DISTANCE: "4"
  DIFFICULTY: "easy"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: minecraftg
  namespace: minecraft
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minecraftg
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5 
  template:
    metadata:
      labels:
        app: minecraftg
    spec:
      containers:
      - name: minecraft
        image: docker.io/itzg/minecraft-bedrock-server:latest
        ports:
        - containerPort: 19132
        - containerPort: 19133
        envFrom:
          - configMapRef:
              name: minecraft-bedrock-env
        volumeMounts:
        - name: azurefileshare
          mountPath: "/data"

      volumes:
      - name: azurefileshare
        azureFile:
          secretName: minecraft-storage-secret
          shareName: bworldaks
          readOnly: false
---
apiVersion: v1
kind: Service
metadata:
  name: minecraftg
  namespace: minecraft
  annotations:
    service.beta.kubernetes.io/azure-dns-label-name: minecraftb
spec:
  type: LoadBalancer
  ports:
  - port: 19132
    targetPort: 19132
    protocol: UDP
    name: mine4
  - port: 19133
    targetPort: 19133
    protocol: UDP
    name: mine6
  selector:
    app: minecraftg 
